export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SETMEETINGID = "SETMEETINGID";
export const SETISMEETINGADMIN = "SETISMEETINGADMIN";
export const SETMEETINGMESSAGE = "SETMEETINGMESSAGE";
export const SETISENDED = "SETISENDED"
export const SETISPRESENTING = "SETISPRESENTING"
export const SETVIDEOFEED = "SETVIDEOFEED"
export const SETAUDIOFEED = "SETAUDIOFEED"
export const RESETMEETINGSTORE = "RESETMEETINGSTORE"

